#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
COMMIT_MSG=$(head -n1 "$COMMIT_MSG_FILE")

# Abort if special commit
if [ "$COMMIT_SOURCE" = "merge" ] || [ "$COMMIT_SOURCE" = "squash" ]; then
    exit 0;
fi

if [ "$COMMIT_MSG" = "" ]; then
    exec < /dev/tty && node_modules/.bin/cz --hook || true
else
    npx  commitlint --edit "$COMMIT_MSG_FILE"
fi